### ISSUE TITLE
chore: have travis deploy to surge on merging to master

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/create-arcgis-app#17]
I think we basically just need to append the following:

```yml
  - yarn run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: create-arcgis-app.surge.sh
  project: ./build/
on:
  branch: master
```
